#!/usr/bin/env python3
"""Generate the synthetic post-mediated xDR sample stream for the `postmed_xdr` pipeline.

Post-mediation output: a mediation platform has already normalised switch-native CDRs
(voice / SMS / data) into one uniform pipe-delimited record layout, rated them, and emitted
one file per collection interval. This generator reproduces that shape.

Everything here is SYNTHETIC and deterministic (fixed seed). PLMNs are in the ITU test range
(001xx), MSISDNs in the +99 reserved range, IMSIs built from the test PLMNs — no real operator
names, numbers or traffic. See the repo rule: sample data is hand-generated, never trimmed
from a capture.

Usage:
    python gen-postmed-xdr.py            # rewrite the sample files next to this script
    python gen-postmed-xdr.py --seed-inbox   # also copy them into the pipeline poll dir
"""

import argparse
import datetime as dt
import pathlib
import random
import shutil

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE / "postmed_xdr"
INBOX = HERE.parents[1] / "data" / "inbox" / "postmed_xdr"

HEADER = [
    "REC_SEQ", "MED_FILE_ID", "SWITCH_ID", "REC_TYPE", "IMSI", "MSISDN",
    "OTHER_PARTY", "CELL_ID", "APN", "START_AT", "EVENT_DATE", "DURATION_SEC",
    "BYTES_UP", "BYTES_DOWN", "RATED_AMOUNT", "CURRENCY", "ROAM_FLAG", "MED_STATUS",
]

SWITCHES = ["MSC-NORTH-01", "MSC-NORTH-02", "SGSN-CENTRAL-01", "MME-SOUTH-03"]
APNS = ["internet.test", "ims.test", "mms.test"]
ROAM = ["HOME", "HOME", "HOME", "NATIONAL", "INTL"]
DAYS = ["2026-09-01", "2026-09-02", "2026-09-03"]
ROWS_PER_DAY = 400


def imsi(rng):
    return "001{:02d}{:010d}".format(rng.choice([3, 6, 19]), rng.randrange(10**9))


def msisdn(rng):
    # +99 is reserved by ITU-T E.164 for trials — never routable.
    return "99{:010d}".format(rng.randrange(10**10))


def record(rng, seq, day, file_id):
    kind = rng.choices(["VOICE", "SMS", "DATA"], weights=[45, 25, 30])[0]
    start = dt.datetime.fromisoformat(day) + dt.timedelta(seconds=rng.randrange(86400))
    roam = rng.choice(ROAM)
    status = rng.choices(["RATED", "RATED", "RATED", "UNRATED", "SUSPENSE"],
                         weights=[70, 10, 10, 6, 4])[0]

    if kind == "VOICE":
        switch = rng.choice(SWITCHES[:2])
        dur, up, down, apn = rng.randrange(5, 3600), "", "", "NULL"
        other = msisdn(rng)
        amount = round(dur / 60 * rng.uniform(0.02, 0.35), 4)
    elif kind == "SMS":
        switch = rng.choice(SWITCHES[:2])
        dur, up, down, apn = 0, "", "", "NULL"
        other = msisdn(rng)
        amount = round(rng.uniform(0.01, 0.08), 4)
    else:
        switch = rng.choice(SWITCHES[2:])
        dur = rng.randrange(30, 7200)
        up, down = rng.randrange(1024, 5_000_000), rng.randrange(4096, 80_000_000)
        apn, other = rng.choice(APNS), "N/A"
        amount = round((up + down) / 1_048_576 * rng.uniform(0.001, 0.02), 4)

    # An UNRATED record leaves mediation with no money on it — that is the real shape,
    # and the reason RATED_AMOUNT must be nullable downstream.
    amount_s = "" if status == "UNRATED" else "{:.4f}".format(amount)

    return [
        "{}-{:06d}".format(day.replace("-", ""), seq),
        file_id,
        switch,
        kind,
        imsi(rng),
        msisdn(rng),
        other,
        "{:05d}-{:03d}".format(rng.randrange(65536), rng.randrange(256)),
        apn,
        start.strftime("%Y-%m-%d %H:%M:%S"),
        day,
        str(dur),
        str(up),
        str(down),
        amount_s,
        "XTS",
        roam,
        status,
    ]


def write(path, rows):
    with path.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write("# post-mediated xDR export — synthetic, generated by gen-postmed-xdr.py\n")
        fh.write("|".join(HEADER) + "\n")
        for row in rows:
            fh.write("|".join(row) + "\n")
    print("wrote {} ({} rows)".format(path.name, len(rows)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed-inbox", action="store_true",
                    help="copy the generated files into the pipeline poll directory")
    args = ap.parse_args()

    rng = random.Random(20260922)
    OUT.mkdir(parents=True, exist_ok=True)

    for day in DAYS:
        file_id = "MED-{}-001".format(day.replace("-", ""))
        rows = [record(rng, i + 1, day, file_id) for i in range(ROWS_PER_DAY)]
        write(OUT / "PMXDR_{}_001.psv".format(day.replace("-", "")), rows)

    # A deliberately defective interval file. Mediation output is not always clean, and a
    # pipeline that has never seen a bad row has not been tested. Kept as a separate file so
    # the happy path stays reproducible.
    bad = [record(rng, i + 1, "2026-09-04", "MED-20260904-001") for i in range(20)]
    bad[3][11] = "not-a-number"          # DURATION_SEC — unparseable integer
    bad[7][10] = "2026-13-45"            # EVENT_DATE — impossible calendar date
    bad[11] = bad[10][:]                 # exact duplicate record
    bad[15] = bad[15][:9]                # short row — truncated mid-write
    write(OUT / "PMXDR_20260904_001.psv.defect", bad)

    if args.seed_inbox:
        INBOX.mkdir(parents=True, exist_ok=True)
        for src in sorted(OUT.glob("*.psv")):
            shutil.copy2(src, INBOX / src.name)
        print("seeded inbox: {}".format(INBOX))


if __name__ == "__main__":
    main()
