{{- if and (not .Values.secrets.existingSecret) .Values.secrets.values }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inspecto.secretName" . }}
  labels: {{- include "inspecto.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets.values | nindent 2 }}
{{- end }}
