import { AttributeSpec } from 'app/inspecto/component-model';

/**
 * The Expectation kind's attribute declarations (C2) — drives `<inspecto-schema-form>` in
 * {@link ExpectationFormDialog}. Identity + target + check kind are required; the kind-specific
 * parameters appear via `dependsOn`; severity/arming are optional (collapsed).
 */
// 'name' (the expectation id) and 'description' are asked at save time (ui-design-review R9 —
// name-at-save), not declared here; see ExpectationFormDialog's `saveForm`.
export const EXPECTATION_ATTRIBUTES: AttributeSpec[] = [
    {
        key: 'targetType',
        label: 'Attach to',
        type: 'select',
        tier: 'required',
        default: 'pipeline',
        options: [
            { value: 'pipeline', label: 'Pipeline' },
            { value: 'job', label: 'Job' },
        ],
    },
    {
        key: 'target',
        label: 'Target',
        type: 'autocomplete',
        tier: 'required',
        placeholder: 'e.g. cdr_ingest',
        help: 'The pipeline or job whose records this check validates.',
    },
    {
        key: 'column',
        label: 'Column',
        type: 'autocomplete',
        tier: 'required',
        // condition names its own field(s) in its tree; baseline profiles its own `columns` list.
        dependsOn: { key: 'kind', in: ['non_null', 'range', 'regex', 'referential'] },
        placeholder: 'e.g. msisdn',
        help: 'The record field the check inspects.',
    },
    {
        key: 'kind',
        label: 'Check',
        type: 'select',
        tier: 'required',
        default: 'non_null',
        options: [
            { value: 'non_null', label: 'Non-null' },
            { value: 'range', label: 'Range' },
            { value: 'regex', label: 'Regex' },
            { value: 'referential', label: 'Referential' },
            { value: 'condition', label: 'Condition (advanced)' },
            { value: 'baseline', label: 'Baseline (vs accepted history)' },
        ],
    },
    // ── baseline (DUCKLE-C8): the current input's profile vs the median of the last N accepted ones ──
    {
        key: 'baselineWindow',
        label: 'Baseline window (accepted runs)',
        type: 'number',
        tier: 'required',
        default: 7,
        min: 1,
        max: 100,
        dependsOn: { key: 'kind', equals: 'baseline' },
        help: 'The baseline is the median of this many most recent accepted profiles.',
    },
    {
        key: 'measures',
        label: 'Measures',
        type: 'list',
        tier: 'required',
        default: ['row_count'],
        dependsOn: { key: 'kind', equals: 'baseline' },
        help: 'Any of row_count, null_count, null_rate, distinct_count, min, max, mean.',
    },
    {
        key: 'columns',
        label: 'Profiled columns',
        type: 'list',
        tier: 'required',
        required: false,
        dependsOn: { key: 'kind', equals: 'baseline' },
        help: 'The columns the per-column measures apply to (not needed for row_count alone).',
    },
    {
        key: 'maxIncrease',
        label: 'Max increase',
        type: 'number',
        tier: 'required',
        required: false,
        min: 0,
        dependsOn: { key: 'kind', equals: 'baseline' },
        help: 'Allowed rise over the baseline. Leave empty for no upper limit (at least one limit is needed).',
    },
    {
        key: 'maxDecrease',
        label: 'Max decrease',
        type: 'number',
        tier: 'required',
        required: false,
        min: 0,
        dependsOn: { key: 'kind', equals: 'baseline' },
        help: 'Allowed fall under the baseline. Leave empty for no lower limit.',
    },
    {
        key: 'limitUnit',
        label: 'Limit unit',
        type: 'select',
        tier: 'required',
        default: 'percent',
        dependsOn: { key: 'kind', equals: 'baseline' },
        options: [
            { value: 'percent', label: '% of the baseline' },
            { value: 'absolute', label: 'Absolute' },
        ],
    },
    {
        key: 'groupBy',
        label: 'Group by',
        type: 'list',
        tier: 'optional',
        dependsOn: { key: 'kind', equals: 'baseline' },
        help: 'Profile each group separately, e.g. region.',
    },
    {
        key: 'requireExistingGroups',
        label: 'A group missing from the input is a failure',
        type: 'boolean',
        tier: 'optional',
        default: false,
        dependsOn: { key: 'kind', equals: 'baseline' },
    },
    {
        key: 'min',
        label: 'Minimum',
        type: 'number',
        tier: 'required',
        dependsOn: { key: 'kind', equals: 'range' },
    },
    {
        key: 'max',
        label: 'Maximum',
        type: 'number',
        tier: 'required',
        dependsOn: { key: 'kind', equals: 'range' },
    },
    {
        key: 'pattern',
        label: 'Pattern (regex)',
        type: 'string',
        tier: 'required',
        dependsOn: { key: 'kind', equals: 'regex' },
        placeholder: '^\\+?[1-9]\\d{6,14}$',
        help: 'Values must fully match this regular expression.',
    },
    {
        key: 'refDataset',
        label: 'Reference dataset',
        type: 'autocomplete',
        tier: 'required',
        dependsOn: { key: 'kind', equals: 'referential' },
        placeholder: 'e.g. tariff_ref',
    },
    {
        key: 'refColumn',
        label: 'Reference column',
        type: 'autocomplete',
        tier: 'required',
        dependsOn: { key: 'kind', equals: 'referential' },
        placeholder: 'e.g. code',
    },
    {
        key: 'severity',
        label: 'Severity of a failure',
        type: 'select',
        tier: 'optional',
        default: 'MAJOR',
        options: [
            { value: 'CRITICAL', label: 'CRITICAL' },
            { value: 'MAJOR', label: 'MAJOR' },
            { value: 'MINOR', label: 'MINOR' },
        ],
        help: 'Severity of the Incident raised when the check fails.',
    },
    { key: 'enabled', label: 'Enabled (evaluated in sweeps)', type: 'boolean', tier: 'optional', default: true },
];
