// One-shot: cut docs/api/openapi-v1.json into per-module fragments + the core fragment (see openapi-fragments.mjs).
// Usage: node tools/openapi-split.mjs [--write]   (dry run by default: prints the plan)
// Run it ONCE to introduce the fragments; afterwards the document is generated by openapi-merge.mjs --write.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CORE_DIR, FRAGMENT, mergeFragments, readManifests, routeShape, splitDocument } from './openapi-fragments.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const docFile = join(root, 'docs/api/openapi-v1.json');
const doc = readFileSync(docFile, 'utf8');
const manifests = readManifests(root).filter((m) => m.routes.length);
const ownerOfShape = new Map();
for (const m of manifests) for (const r of m.routes) ownerOfShape.set(r.shape, m.id);

const { core, modules } = splitDocument(doc, (key) => ownerOfShape.get(routeShape(key)) ?? null);
const dirOf = new Map(manifests.map((m) => [m.id, m.dir]));
const fragments = [...modules].map(([name, text]) => ({ name, text }));

if (mergeFragments(core, fragments) !== doc) { console.error('split would not merge back byte-identically; nothing written'); process.exit(1); }
console.log(`core: ${core.length} bytes`);
for (const [id, text] of modules) console.log(`${dirOf.get(id)}: ${text.length} bytes`);
if (process.argv.includes('--write')) {
  const put = (dir, text) => { const f = join(root, dir, FRAGMENT); mkdirSync(dirname(f), { recursive: true }); writeFileSync(f, text); };
  put(CORE_DIR, core);
  for (const [id, text] of modules) put(dirOf.get(id), text);
  console.log('written');
}
